# Generated by Django 4.2.1 on 2023-06-20 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "user_id",
                    models.CharField(
                        max_length=20, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=5)),
                ("email", models.EmailField(max_length=30, unique=True)),
                ("phone_num", models.CharField(max_length=11)),
                ("emergency", models.CharField(max_length=11)),
                ("address", models.CharField(max_length=50)),
                ("gender", models.CharField(max_length=5)),
                ("birth", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
