# Generated by Django 4.2 on 2023-06-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SignIn", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(max_length=10),
        ),
    ]
