# Generated by Django 4.2 on 2023-07-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SignIn", "0002_alter_user_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="medical_info",
            field=models.CharField(blank=True, default="", max_length=500, null=True),
        ),
    ]
