# Generated by Django 4.2 on 2023-06-30 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_rename_user_danger_user_id_danger_user_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="danger",
            old_name="user_id",
            new_name="user",
        ),
    ]
