# Generated by Django 4.2 on 2023-06-30 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_rename_user_id_danger_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="danger",
            name="user_name",
        ),
    ]
