# Generated by Django 4.2 on 2023-06-13 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="id",
        ),
        migrations.RemoveField(
            model_name="history",
            name="id",
        ),
        migrations.RemoveField(
            model_name="post",
            name="id",
        ),
        migrations.AlterField(
            model_name="comment",
            name="comment_id",
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="history",
            name="hist_id",
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="post",
            name="post_id",
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
