# Generated by Django 4.2 on 2023-06-13 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0002_remove_comment_id_remove_history_id_remove_post_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
