# Generated by Django 4.2.1 on 2023-06-14 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0005_alter_post_user_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="user_id",
            new_name="writer",
        ),
    ]
