# Generated by Django 4.2 on 2023-06-19 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0011_remove_comment_post_id_remove_comment_user_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Audio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("audio", models.FileField(upload_to="audio/")),
            ],
        ),
    ]
