# Generated by Django 4.2 on 2023-06-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0013_remove_history_user_id_history_danger_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audio",
            name="audio",
            field=models.FileField(upload_to="sound/"),
        ),
    ]
