# Generated by Django 4.2 on 2023-07-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0015_setting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="history",
            name="file",
            field=models.CharField(max_length=500),
        ),
    ]
