"""
Django settings for hearo project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

import firebase_admin
from firebase_admin import credentials

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

cred_path = os.path.join(BASE_DIR, "serviceAccountKey.json")
cred = credentials.Certificate(cred_path)
firebase_admin.initialize_app(cred)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-w1kwtykgu6-==f@2=6p7!!b0qax2gkr#mw44$r0ntfb%j5l6u!"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_extensions",
    "django.core.files",
    "django.core.files.storage",
    "Main",
    "SignIn",
    "app",
    'storages',
    'AI',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "hearo.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [f'{BASE_DIR}/templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "hearo.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "ko-kr"

TIME_ZONE = "Asia/Seoul"

USE_I18N = True

USE_L10N = True

USE_TZ = False  # False 로 설정해야 DB에 변경 된 TIME_ZONE 이 반영 됨 


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/



# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# mysql 연결 안됨 ㅠ
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'HOST': 'localhost',
#         'PORT': '3306',
#         'NAME': 'root',
#         'PASSWORD': 'aivle',
#     },
# }

LOGIN_URL = '/' # 로그인 필요할시 이동할 경로

LOGIN_REDIRECT_URL = '/Main'

AUTH_USER_MODEL = 'SignIn.User'

MESSAGE_STORAGE = 'django.contrib.messages.storage.fallback.FallbackStorage'

CSRF_TRUSTED_ORIGINS = ['https://*.ngrok-free.app']


# AWS Settings
AWS_ACCESS_KEY_ID = 'AKIATTZIKJQIZZDCF6GB'
AWS_SECRET_ACCESS_KEY = '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'
AWS_STORAGE_BUCKET_NAME = 'hearo-sound'
AWS_S3_REGION_NAME = 'ap-northeast-2' 
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

# Message Settings
MESSAGE_ACCESS_KEY = "WQUb7qonyYwsyd5tVTq5"
MESSAGE_SECRET_KEY = "Y3Tly6hynzLr6YihqDIBNtFbyaqZByckHnZkri9u"
MESSAGE_SERVICE_KEY = "ncp:sms:kr:310676496896:hearo"

# Shorten URL Settings
SHORTEN_URL_CLIENT_ID = 'sY1w6Xtbo4ruq8fCi6M3'
SHORTEN_URL_CLIENT_SECRET = 'fwTWWdYiml'

#FCM Settings
FCM_SERVER_KEY = '8VJGftM-po3F7MrkN2aOQ4eNfjP_qqS11zhwokL3FGM'
FCM_PROJECT_ID = 'hearo-78135'